global using Ardalis.Result;
global using Ardalis.SharedKernel;
global using AutoMapper;
global using DealMatcher.Backend.Core.Aggregates.Category;
global using DealMatcher.Backend.Core.Aggregates.User;
global using DealMatcher.Backend.Infrastructure.Data;
global using DealMatcher.Backend.UseCases.Features.Offer.Get;
global using DealMatcher.Backend.UseCases.Mapping.Profiles;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using NSubstitute;
global using Shouldly;
global using Xunit;
global using CategoryEntity = DealMatcher.Backend.Core.Aggregates.Category.Category;
global using OfferEntity = DealMatcher.Backend.Core.Aggregates.Offer.Offer;
global using UserEntity = DealMatcher.Backend.Core.Aggregates.User.User;
