<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="OneOf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DealMatcher.Backend.Core\DealMatcher.Backend.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Activity\" />
  </ItemGroup>

</Project>
