<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DealMatcher.Backend.Core\DealMatcher.Backend.Core.csproj" />
  </ItemGroup>

</Project>
