global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Ardalis.Result;
global using Ardalis.SharedKernel;
global using AutoMapper;
global using DealMatcher.Backend.Core.Aggregates.Admin;
global using DealMatcher.Backend.Core.Aggregates.Admin.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Admin.Specifications;
global using DealMatcher.Backend.Core.Aggregates.Ban.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Ban.Specifications;
global using DealMatcher.Backend.Core.Aggregates.Cart;
global using DealMatcher.Backend.Core.Aggregates.Cart.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Cart.Specifications;
global using DealMatcher.Backend.Core.Aggregates.Category.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Category.Specifications;
global using DealMatcher.Backend.Core.Aggregates.Offer;
global using DealMatcher.Backend.Core.Aggregates.Offer.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Offer.Specifications;
global using DealMatcher.Backend.Core.Aggregates.Payment;
global using DealMatcher.Backend.Core.Aggregates.Payment.DTOs;
global using DealMatcher.Backend.Core.Aggregates.User;
global using DealMatcher.Backend.Core.Aggregates.User.DTOs;
global using DealMatcher.Backend.Core.Aggregates.User.Specifications;
global using DealMatcher.Backend.Core.Events;
global using DealMatcher.Backend.Core.Interfaces;
global using DealMatcher.Backend.UseCases.Features.Cart.DTOs;
global using DealMatcher.Backend.UseCases.Mapping.Profiles;
global using MediatR;
global using Microsoft.Extensions.Configuration;
global using BanEntity = DealMatcher.Backend.Core.Aggregates.Ban.Ban;
global using CategoryEntity = DealMatcher.Backend.Core.Aggregates.Category.Category;
global using ConversationEntity = DealMatcher.Backend.Core.Aggregates.Conversation.Conversation;
global using MessageEntity = DealMatcher.Backend.Core.Aggregates.Conversation.Message;
global using OfferEntity = DealMatcher.Backend.Core.Aggregates.Offer.Offer;
global using UserEntity = DealMatcher.Backend.Core.Aggregates.User.User;
