global using Ardalis.Result;
global using Ardalis.SharedKernel;
global using AutoMapper;
global using DealMatcher.Backend.Core.Aggregates.Cart;
global using DealMatcher.Backend.Core.Aggregates.Cart.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Category.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Offer.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Offer.Specifications;
global using DealMatcher.Backend.Core.Aggregates.User;
global using DealMatcher.Backend.Core.Aggregates.User.DTOs;
global using DealMatcher.Backend.Core.Aggregates.User.Specifications;
global using DealMatcher.Backend.Core.Interfaces;
global using DealMatcher.Backend.UseCases.Mapping.Profiles;
global using MediatR;
global using CategoryEntity = DealMatcher.Backend.Core.Aggregates.Category.CategoryEnity;
global using OfferEntity = DealMatcher.Backend.Core.Aggregates.Offer.Offer;
global using UserEntity = DealMatcher.Backend.Core.Aggregates.User.User;
