global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using DealMatcher.Backend.Core;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Shouldly;
global using Xunit;
global using DealMatcher.Backend.Core.Aggregates.Offer;
global using DealMatcher.Backend.Core.Aggregates.User;
global using DealMatcher.Backend.Core.Aggregates.Category;
global using DealMatcher.Backend.Core.Aggregates.Offer.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Category.DTOs;
global using AutoMapper;
global using DealMatcher.Backend.UseCases.Mapping.Profiles;
global using Serilog.Extensions.Logging;
global using DealMatcher.Backend.UseCases.Features.Offer.Get;
global using OfferEntity = DealMatcher.Backend.Core.Aggregates.Offer.Offer;
global using UserEntity = DealMatcher.Backend.Core.Aggregates.User.User;
global using CategoryEntity = DealMatcher.Backend.Core.Aggregates.Category.Category;
