global using System.Runtime.CompilerServices;
global using Ardalis.Result;
global using Ardalis.SharedKernel;
global using AutoMapper;
global using DealMatcher.Backend.Core;
global using DealMatcher.Backend.Core.Aggregates.Cart.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Category;
global using DealMatcher.Backend.Core.Aggregates.Category.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Offer;
global using DealMatcher.Backend.Core.Aggregates.Offer.DTOs;
global using DealMatcher.Backend.Core.Aggregates.Offer.Specifications;
global using DealMatcher.Backend.Core.Aggregates.User;
global using DealMatcher.Backend.Core.Aggregates.User.DTOs;
global using DealMatcher.Backend.Core.Aggregates.User.Specifications;
global using DealMatcher.Backend.Core.Interfaces;
global using DealMatcher.Backend.UseCases.Features.Offer.Get;
global using DealMatcher.Backend.UseCases.Features.Offer.Search;
global using DealMatcher.Backend.UseCases.Features.User.Delete;
global using DealMatcher.Backend.UseCases.Features.User.Login;
global using DealMatcher.Backend.UseCases.Features.User.Offers;
global using DealMatcher.Backend.UseCases.Features.User.Register;
global using DealMatcher.Backend.UseCases.Features.User.Update;
global using DealMatcher.Backend.UseCases.Mapping.Profiles;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Serilog.Extensions.Logging;
global using Shouldly;
global using Xunit;
global using CartItemEntity = DealMatcher.Backend.Core.Aggregates.Cart.CartItem;
global using CategoryEntity = DealMatcher.Backend.Core.Aggregates.Category.CategoryEnity;
global using OfferEntity = DealMatcher.Backend.Core.Aggregates.Offer.Offer;
global using UserEntity = DealMatcher.Backend.Core.Aggregates.User.User;
global using DealMatcher.Backend.Infrastructure.Authentication;
global using Microsoft.Extensions.Configuration;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Microsoft.IdentityModel.Tokens;
